### PR TITLE
add basic google analytics to site

### PR DESCRIPTION
**Pull request by b5**
I think we should get a sense of weather people are actually coming back to this project after seeing it work. This adds basic google analytics with a tracking ID we can transfer to any EDGI google analytics account once this is merged.

### CODE REVIEW

**Review by osterbit — APPROVED** [review]
👍 👍

**Comment by dcwalk** [comment]
In general I'm fine with this, however I'd like to notify in some way that we have analytics enabled in text on the page (I'm used to somewhat longer privacy policies if any tracking is happening and I think that is a level to far, but not mentioning anything seems also a little odd)

and it should be shared with the main EDGI gmail

**Comment by Frijol** [comment]
oh I'm really glad this already exists! I wanted to make sure we had analytics before sending to users, so we could find out regularity of use.

@dcwalk good point re letting users know we're tracking. I think you're requesting:

* In order to land, this PR should add text anywhere on the page that says we're using analytics to understand how people are using this tool

Is that right?

**Comment by b5** [comment]
Hey team! Implementing pagination will take a little too long at the moment, so instead I've bumped the max number of results returned to 1000, which will remove the need for pagination at all for most meaningful queries. (searches like "a" or "is" will probably return more than 1k results, but I don't think this is a big deal).

I've also added text in the top right that says "eis search uses analytics to track usage", @dcwalk I'll get the EDGI gmail from you on slack & share analytics. Does this sound good to everyone?

**Review by Frijol — APPROVED** [review]
LGTM, other than– I'd change the title of the PR to make it clear this also changes the page length.

I didn't do a thorough code review, but ran it locally & it looks good there.

Excited to see this land!

**Comment by dcwalk** [comment]
@b5 -- is @Frijol able to set you up on analytics using the envirodgi@gmail?

**Comment by Frijol** [comment]
@dcwalk I don't think *I* have access to that account!

**Pull request merged**
